language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
    - gem install cocoapods -v '0.29.0'
script: xctool -workspace GQFlowController.xcworkspace -scheme GQFlowController -sdk iphonesimulator test
