language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
script: xctool -workspace GQFlowController.xcworkspace -scheme GQFlowController -sdk iphonesimulator test
