language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
    - sudo mkdir -p /usr/local/bin
    - sudo cp app/moarfonts /usr/local/bin
    - sudo cp app/app/Fonts/* $HOME/Library/Fonts
script: xctool -workspace GQFlowController.xcworkspace -scheme GQFlowController -sdk iphonesimulator test
